AAA

diff --git a/buildroot/share/git/mfprep b/buildroot/share/git/mfprep
--- a/buildroot/share/git/mfprep
+++ b/buildroot/share/git/mfprep
@@ -2,6 +2,7 @@
 #
 # mfprep tag1 [tag2]
 #
+<<<<<<< HEAD
 # Find commits in bugfix-2.0.x that are not yet in 2.0.x.
 #
 # Specify a version tag to start from, and optional version tag to end at.
@@ -10,6 +11,15 @@
 #
 
 SED=$(which gsed sed | head -n1)
+=======
+# Find commits in bugfix-2.1.x that are not yet in 2.1.x.
+#
+# Specify a version tag to start from, and optional version tag to end at.
+# For bugfix-2.1.x the tag will be prefixed by dev- to distinguish it from the version tag,
+# so at every release be sure to create a dev- tag and publish it to origin.
+#
+
+>>>>>>> origin/release-2.1.3-beta2
 SELF=`basename "$0"`
 DRYRUN=0
 
@@ -18,6 +28,7 @@ DRYRUN=0
 TAG1=$1
 TAG2=${2:-"HEAD"}
 
+<<<<<<< HEAD
 DEST=2.0.x
 
 # Validate that the required tags exist
@@ -28,6 +39,18 @@ MTAG=`git tag | grep -e "^$TAG1\$"`
 [[ -n "$MTAG" ]] || { echo "Can't find tag $TAG1" ; exit 1 ; }
 
 # Generate log of recent commits for bugfix-2.0.x and DEST
+=======
+DEST=2.1.x
+
+# Validate that the required tags exist
+
+MTAG=`git tag | grep -e "^dev-$TAG1\$"`
+[[ -n "$MTAG" ]] || { echo "Can't find tag dev-$TAG1" ; exit 1 ; }
+MTAG=`git tag | grep -e "^$TAG1\$"`
+[[ -n "$MTAG" ]] || { echo "Can't find tag $TAG1" ; exit 1 ; }
+
+# Generate log of recent commits for bugfix-2.1.x and DEST
+>>>>>>> origin/release-2.1.3-beta2
 
 TMPDIR=`mktemp -d`
 LOGB="$TMPDIR/log-bf.txt"
@@ -35,11 +58,19 @@ LOG2="$TMPDIR/log-2x.txt"
 TMPF="$TMPDIR/tmp.txt"
 SCRF="$TMPDIR/update-$DEST.sh"
 
+<<<<<<< HEAD
 git checkout bugfix-2.0.x
 git log --pretty="[%h] %s" bf-$TAG1..$TAG2 | grep -v '\[cron\]' | $SED '1!G;h;$!d' >"$LOGB"
 
 git checkout $DEST
 git log --pretty="[%h] %s" $TAG1..$TAG2 | $SED '1!G;h;$!d' >"$LOG2" || { echo "Can't find tag bf-$TAG1" ; exit 1 ; }
+=======
+git checkout bugfix-2.1.x
+git log --pretty="[%h] %s" dev-$TAG1..$TAG2 | grep -v '\[cron\]' | sed '1!G;h;$!d' >"$LOGB"
+
+git checkout $DEST
+git log --pretty="[%h] %s" $TAG1..$TAG2 | sed '1!G;h;$!d' >"$LOG2" || { echo "Can't find tag dev-$TAG1" ; exit 1 ; }
+>>>>>>> origin/release-2.1.3-beta2
 
 # Go through commit text from DEST removing all matches from the bugfix log
 
@@ -57,7 +88,11 @@ cat "$LOG2" | while read line; do
     #echo "... $PATT"
     [[ -n "$PATT" ]] && { grep -vE "$PATT" "$LOGB" >"$TMPF" ; cp "$TMPF" "$LOGB" ; }
   else
+<<<<<<< HEAD
     PATT=$( $SED -E 's/^\[[0-9a-f]{10}\]( . )?(.+)$/\2/' <<<"$line" )
+=======
+    PATT=$( sed -E 's/^\[[0-9a-f]{10}\]( . )?(.+)$/\2/' <<<"$line" )
+>>>>>>> origin/release-2.1.3-beta2
     [[ -n "$PATT" ]] && { grep -v "$PATT" "$LOGB" >"$TMPF" ; cp "$TMPF" "$LOGB" ; }
   fi
 done
